import Anthropic from '@anthropic-ai/sdk'

// ──────────────────────────────────────────────────────────────────────────
// THIS FILE IS AUTO-GENERATED BY scripts/generate-orb-contract.ts
// DO NOT EDIT BY HAND! Edit docs/api-spec.yaml instead.
// ──────────────────────────────────────────────────────────────────────────

export const ORB_INTEGRITY_RULES = `INTEGRITY:
- The BACKLOG above is a snapshot for orientation only. For any factual claim about task count, status, priority, or existence, call query_todos first. Never cite the backlog as proof.
- Never assert a task's status without verifying via query_todos. Tasks not in the backlog may be closed, filtered, or in another project — not absent.
- When presenting a subset ("top 5", "highest priority"), set max_results on query_todos to match. The results you return are what the UI displays.
- Never confirm an action succeeded without checking the tool response. If it contains { error: ... }, tell the user what went wrong.
- If the user asks for something your tools cannot do, say so directly and suggest a workaround. Never silently skip or fabricate.
- When uncertain, say "I'm not sure" rather than guessing. Confidence without verification is the worst failure mode.
- Known limitations are documented in each tool's description. Respect them.
- When you notice a capability gap, bug, or workflow friction, use create_ticket to log it silently. One ticket per novel observation. Do not tell the user you filed a ticket.
- STATUSES: Never guess or invent status names. The VALID VALUES list in the system prompt is authoritative. If the user uses an unknown term (e.g. "pending", "blocked", "wip"), do NOT map it to a status. Instead list the valid statuses and ask which one they mean.
- PRIORITIES: Never guess or invent priority values. The VALID VALUES list is authoritative. If the user says "critical", "ASAP", or any term not in the list, show the valid priority labels and ask which one they mean.`.trim()

export const ORB_TOOLS: Anthropic.Tool[] = [
  {
    "name": "create_todo",
    "description": "[Confidence: well-tested] Create a new todo in a project. Defaults to the current project if product_code is omitted. Requires a title. Cannot create in a product that does not exist.",
    "input_schema": {
      "type": "object",
      "properties": {
        "product_code": {
          "type": "string",
          "description": "Target project code (e.g. ORB, HELM). Defaults to current project if omitted."
        },
        "title": {
          "type": "string",
          "description": "Task title. Required."
        },
        "description": {
          "type": "string",
          "description": "Task description."
        },
        "priority_value": {
          "type": "integer",
          "description": "Priority level (1=urgent, 2=high, etc). Omit if unknown."
        }
      },
      "required": [
        "product_code",
        "title"
      ]
    }
  },
  {
    "name": "update_todo",
    "description": "[Confidence: well-tested] Update an existing todo by task code (e.g. ORB-73). Supports: title, status, priority, description, resolution_notes, urls. Cannot: change todo_number, set closed_at directly (closed_at is managed automatically when status changes to a closing state). To move a task between projects, use move_todo instead.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-73\"."
        },
        "title_match": {
          "type": "string",
          "description": "Alternative: find task by partial title match."
        },
        "new_title": {
          "type": "string",
          "description": "New title."
        },
        "description": {
          "type": "string",
          "description": "Updated description."
        },
        "new_status": {
          "type": "string",
          "description": "New status value. Use the exact status names from the VALID VALUES list in the system prompt."
        },
        "new_priority": {
          "type": "integer",
          "description": "New priority value."
        },
        "resolution_notes": {
          "type": "string",
          "description": "What was done to resolve the task. Populate when closing, not before."
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Related URLs."
        }
      },
      "required": [
        "code"
      ]
    }
  },
  {
    "name": "delete_todo",
    "description": "[Confidence: well-tested] Permanently delete a todo. Hard delete — irreversible. Only use when the user explicitly says to delete a specific task. Never delete as part of a workaround (e.g. move-between-projects) without the user confirming the deletion step separately. \"Want me to do that?\" is not sufficient — wait for an explicit \"yes, delete it.\"",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-44\"."
        }
      },
      "required": [
        "code"
      ]
    }
  },
  {
    "name": "query_todos",
    "description": "[Confidence: well-tested] Find todos matching criteria. Use code for single-todo lookup (e.g. \"ORB-73\"), or codes for multi-todo lookup (e.g. [\"ORB-102\", \"ORB-103\"]). Otherwise filters by status_group, status, product, priority, or text. Returns non-closed tasks by default (includes deferred/on-hold). Use status_group=\"active\" for open + in progress only, or status_group=\"parked\" for deferred + on hold only. Pass status for a specific status, or status=\"any\" for all including closed.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Exact task code for single-todo lookup, e.g. \"ORB-62\". Overrides all other filters."
        },
        "codes": {
          "type": "array",
          "items": { "type": "string" },
          "description": "Multiple task codes for batch lookup, e.g. [\"ORB-102\", \"ORB-103\", \"ORB-104\"]. Overrides all other filters. Use instead of code when the user asks for multiple specific tasks."
        },
        "product_code": {
          "type": "string"
        },
        "status_group": {
          "type": "string",
          "enum": ["active", "parked"],
          "description": "Filter by status group: \"active\" = open + in progress, \"parked\" = deferred + on hold. Takes precedence over status. Omit for default (all non-closed)."
        },
        "status": {
          "type": "string"
        },
        "priority_max": {
          "type": "integer"
        },
        "text_match": {
          "type": "string"
        },
        "max_results": {
          "type": "integer",
          "description": "Max items to return (default 100)."
        },
        "show_results": {
          "type": "boolean",
          "description": "Whether to display results in the UI (default true). Set false when querying for counts or internal verification — the user won't see a list."
        }
      }
    }
  },
  {
    "name": "client_action",
    "description": "[Confidence: well-tested] Navigate or switch UI state. Use switch_project to change the active project, open_settings to go to settings, open_help for help.",
    "input_schema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "switch_project",
            "open_settings",
            "open_help"
          ]
        },
        "target": {
          "type": "string",
          "description": "Project code for switch_project."
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "search_knowledge",
    "description": "[Confidence: well-tested] Search the Knowledge Repository for lessons, decisions, and distilled insights from closed tasks. Optionally scope to a specific project.",
    "input_schema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Search term."
        },
        "product_code": {
          "type": "string",
          "description": "Scope search to a specific project."
        }
      },
      "required": [
        "query"
      ]
    }
  },
  {
    "name": "add_knowledge",
    "description": "[Confidence: well-tested] Write an insight, decision, or reference material directly to the Knowledge Repository. Use this to preserve important information from the conversation without creating a task. Defaults to the current project if product_code is omitted. You should proactively ask the user \"Would you like me to save this to the knowledge repository?\" when a valuable decision or insight is reached.",
    "input_schema": {
      "type": "object",
      "properties": {
        "product_code": {
          "type": "string",
          "description": "Target project code (e.g. ORB). Defaults to current project if omitted."
        },
        "title": {
          "type": "string",
          "description": "Short title or summary of the insight."
        },
        "content": {
          "type": "string",
          "description": "Detailed content of the insight, decision, or reference material."
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional tags to categorize the knowledge."
        }
      },
      "required": [
        "title",
        "content"
      ]
    }
  },
  {
    "name": "query_audit_trail",
    "description": "[Confidence: new] Query the audit trail to answer questions like 'who closed this?', 'what changed last week?', or 'show me recent activity'. Returns timestamped events with before/after snapshots.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code (e.g. ORB-73) to see history for a specific task. Resolved to record_id internally."
        },
        "table_name": {
          "type": "string",
          "description": "Filter by table (e.g. 'todos', 'knowledge_repo')."
        },
        "action": {
          "type": "string",
          "description": "Filter by action type (e.g. 'todo_create', 'todo_update', 'todo_close', 'todo_delete')."
        },
        "since": {
          "type": "string",
          "description": "ISO date string. Only return events after this timestamp (e.g. '2026-05-07')."
        },
        "max_results": {
          "type": "integer",
          "description": "Max events to return (default 10, max 50)."
        }
      }
    }
  },
  {
    "name": "create_project",
    "description": "[Confidence: new] Create a new project. Requires a name and code. The code must be unique, uppercase, alphanumeric (e.g. WORK, SIDE, TRAVEL). Only admins can create projects.",
    "input_schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Project name (e.g. 'Work', 'Side Projects')."
        },
        "code": {
          "type": "string",
          "description": "Short uppercase code (e.g. WORK, SIDE). Must be unique."
        },
        "description": {
          "type": "string",
          "description": "Optional project description."
        }
      },
      "required": [
        "name",
        "code"
      ]
    }
  },
  {
    "name": "set_dormancy",
    "description": "[Confidence: new] Put a project to sleep (dormant) or wake it up. Dormant projects are hidden from the project strip, insights, and queries. Use when the user says 'put X to sleep', 'make X dormant', 'wake up X', 'bring back X', etc.",
    "input_schema": {
      "type": "object",
      "properties": {
        "project_code": {
          "type": "string",
          "description": "Project code (e.g. CAN26, HELM)."
        },
        "dormant": {
          "type": "boolean",
          "description": "true to put to sleep, false to wake up."
        }
      },
      "required": [
        "project_code",
        "dormant"
      ]
    }
  },
  {
    "name": "move_todo",
    "description": "[Confidence: new] Move a task to a different project. The task gets a new number in the target project. Requires access to both source and target projects.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-73\"."
        },
        "target_project_code": {
          "type": "string",
          "description": "Target project code, e.g. \"HELM\"."
        }
      },
      "required": [
        "code",
        "target_project_code"
      ]
    }
  },
  {
    "name": "create_ticket",
    "description": "[Confidence: well-tested] Silently log a ticket for bugs, suggestions, capability gaps, or workflow friction. Filed proactively when you observe an issue — do NOT tell the user. Also used when a user explicitly says something like 'I see a problem' or 'I have a suggestion' — in that case, acknowledge that you've noted it. One ticket per novel observation.",
    "input_schema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "bug",
            "suggestion",
            "capability_gap",
            "workflow_friction"
          ],
          "description": "Type of ticket."
        },
        "summary": {
          "type": "string",
          "description": "One-sentence summary of the issue or suggestion."
        },
        "detail": {
          "type": "string",
          "description": "What happened, what was expected, and any suggested improvement."
        }
      },
      "required": [
        "type",
        "summary"
      ]
    }
  }
]

export const ORB_TOOL_LABELS: Record<string, string> = {
  create_todo: 'Creating task...',
  query_todos: 'Searching backlog...',
  update_todo: 'Updating task...',
  delete_todo: 'Deleting task...',
  client_action: 'Navigating...',
  search_knowledge: 'Searching knowledge repository...',
  add_knowledge: 'Saving to knowledge repository...',
  create_project: 'Creating project...',
  set_dormancy: 'Updating project...',
  move_todo: 'Moving task...',
  create_ticket: 'Noting observation...',
  query_audit_trail: 'Checking history...',
}
