import Anthropic from '@anthropic-ai/sdk'

// ──────────────────────────────────────────────────────────────────────────
// THIS FILE IS AUTO-GENERATED BY scripts/generate-orb-contract.ts
// DO NOT EDIT BY HAND! Edit docs/api-spec.yaml instead.
// ──────────────────────────────────────────────────────────────────────────

export const ORB_INTEGRITY_RULES = `INTEGRITY:\n- Never confirm an action succeeded without checking the tool response. If it contains { error: ... }, tell the user what went wrong.\n- If the user asks for something your tools cannot do, say so directly and suggest a workaround if one exists. Never silently skip or fabricate.\n- Known limitations are documented in each tool's description. Respect them.\n- When you notice a recurring gap between what users expect and what you can do, use report_friction to log the observation. Use sparingly — one report per novel pattern, not every interaction.\n`.trim()

export const ORB_TOOLS: Anthropic.Tool[] = [
  {
    "name": "create_todo",
    "description": "[Confidence: well-tested] Create a new todo in a project. Defaults to the current project if product_code is omitted. Requires a title. Cannot create in a product that does not exist.",
    "input_schema": {
      "type": "object",
      "properties": {
        "product_code": {
          "type": "string",
          "description": "Target project code (e.g. ORB, HELM). Defaults to current project if omitted."
        },
        "title": {
          "type": "string",
          "description": "Task title. Required."
        },
        "description": {
          "type": "string",
          "description": "Task description."
        },
        "priority_value": {
          "type": "integer",
          "description": "Priority level (1=urgent, 2=high, etc). Omit if unknown."
        }
      },
      "required": [
        "product_code",
        "title"
      ]
    }
  },
  {
    "name": "update_todo",
    "description": "[Confidence: well-tested] Update an existing todo by task code (e.g. ORB-73). Supports: title, status, priority, description, resolution_notes, urls. Cannot: move a task between products, change todo_number, set closed_at directly (closed_at is managed automatically when status changes to a closing state). If the user asks to move a task between products, explain the limitation and offer to create a new task in the target product + delete the original as a workaround.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-73\"."
        },
        "title_match": {
          "type": "string",
          "description": "Alternative: find task by partial title match."
        },
        "new_title": {
          "type": "string",
          "description": "New title."
        },
        "description": {
          "type": "string",
          "description": "Updated description."
        },
        "new_status": {
          "type": "string",
          "enum": [
            "open",
            "done"
          ],
          "description": "New status value."
        },
        "new_priority": {
          "type": "integer",
          "description": "New priority value."
        },
        "resolution_notes": {
          "type": "string",
          "description": "What was done to resolve the task. Populate when closing, not before."
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Related URLs."
        }
      },
      "required": [
        "code"
      ]
    }
  },
  {
    "name": "delete_todo",
    "description": "[Confidence: well-tested] Permanently delete a todo. Hard delete — irreversible. Only use when the user explicitly says to delete a specific task. Never delete as part of a workaround (e.g. move-between-projects) without the user confirming the deletion step separately. \"Want me to do that?\" is not sufficient — wait for an explicit \"yes, delete it.\"",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Task code, e.g. \"ORB-44\"."
        }
      },
      "required": [
        "code"
      ]
    }
  },
  {
    "name": "query_todos",
    "description": "[Confidence: well-tested] Find todos matching criteria. Use code for single-todo lookup (e.g. \"ORB-73\"). Otherwise filters by status, product, priority, or text. Returns open tasks by default — pass status to include closed.",
    "input_schema": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "Exact task code for single-todo lookup, e.g. \"ORB-62\". Overrides all other filters."
        },
        "product_code": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "priority_max": {
          "type": "integer"
        },
        "text_match": {
          "type": "string"
        },
        "max_results": {
          "type": "integer"
        }
      }
    }
  },
  {
    "name": "client_action",
    "description": "[Confidence: well-tested] Navigate or switch UI state. Use switch_project to change the active project, open_settings to go to settings, open_help for help.",
    "input_schema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "switch_project",
            "open_settings",
            "open_help"
          ]
        },
        "target": {
          "type": "string",
          "description": "Project code for switch_project."
        }
      },
      "required": [
        "action"
      ]
    }
  },
  {
    "name": "search_knowledge",
    "description": "[Confidence: well-tested] Search the Knowledge Repository for lessons, decisions, and distilled insights from closed tasks. Optionally scope to a specific project.",
    "input_schema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Search term."
        },
        "product_code": {
          "type": "string",
          "description": "Scope search to a specific project."
        }
      },
      "required": [
        "query"
      ]
    }
  },
  {
    "name": "add_knowledge",
    "description": "[Confidence: well-tested] Write an insight, decision, or reference material directly to the Knowledge Repository. Use this to preserve important information from the conversation without creating a task. Defaults to the current project if product_code is omitted. You should proactively ask the user \"Would you like me to save this to the knowledge repository?\" when a valuable decision or insight is reached.",
    "input_schema": {
      "type": "object",
      "properties": {
        "product_code": {
          "type": "string",
          "description": "Target project code (e.g. ORB). Defaults to current project if omitted."
        },
        "title": {
          "type": "string",
          "description": "Short title or summary of the insight."
        },
        "content": {
          "type": "string",
          "description": "Detailed content of the insight, decision, or reference material."
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional tags to categorize the knowledge."
        }
      },
      "required": [
        "title",
        "content"
      ]
    }
  },
  {
    "name": "report_friction",
    "description": "[Confidence: well-tested] Log an observation about a capability gap, user confusion, or workflow friction you have noticed. Use when you see something the system should handle better — a missing feature users keep asking for, a confusing interaction pattern, or a limitation that deserves a workaround. Use sparingly: one report per novel observation, not for routine interactions.",
    "input_schema": {
      "type": "object",
      "properties": {
        "category": {
          "type": "string",
          "enum": [
            "capability_gap",
            "user_confusion",
            "data_quality",
            "workflow_friction",
            "suggestion"
          ],
          "description": "Type of friction observed."
        },
        "summary": {
          "type": "string",
          "description": "One-sentence summary of the friction observed."
        },
        "detail": {
          "type": "string",
          "description": "What the user asked for, what you tried, what went wrong or was missing, and any suggested improvement."
        }
      },
      "required": [
        "category",
        "summary"
      ]
    }
  }
]

export const ORB_TOOL_LABELS: Record<string, string> = {
  create_todo: 'Creating task...',
  query_todos: 'Searching backlog...',
  update_todo: 'Updating task...',
  delete_todo: 'Deleting task...',
  client_action: 'Navigating...',
  search_knowledge: 'Searching knowledge repository...',
  add_knowledge: 'Saving to knowledge repository...',
  report_friction: 'Logging observation...',
}
